apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: myapp
type: Opaque
stringData:
  # mp 
  ACCESS_TOKEN_MP:

  # paypal
  PAYPAL_CLIENT_ID:
  PAYPAL_SECRET:

  # auth0
  AUTH0_DOMAIN:
  AUTH0_AUDIENCE:
  AUTH0_MGMT_CLIENT_ID:
  AUTH0_MGMT_CLIENT_SECRET:
  CLIENT_ORIGIN_URL: