apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: matiasherrneder/mipla-backend:latest  # <-- Cambiá esto por tu imagen en Docker Hub
          envFrom:
            - configMapRef:
                name: backend-env
          ports:
            - containerPort: 8002
          command: ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload"]

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
